### ISSUE TITLE
Add LICENSE to the repository?

### ISSUE THREAD

**Issue by lubianat** [frankkramer-lab/DrNote#1]
Hello, congrats on the great tool! Can't wait to use it :) 

By the way, could you add a license file to the repository to clarify reuse rules? Thanks!

**Comment by j-frei** [comment]
Hello @lubianat,

Thank you for your interest in our tool and for pointing out the missing license file.
I've added the license information to the repository.
Feel free to share feedback or your use cases of our tool with us. :)

Kind regards,
Johann
